import { getState } from "../main/initApp.js";
import origins from "../data/templates/origins.js";

export function addParams({ links }) {
  const country = getState("country");

  return links.map((link) => {
    if ("query" in link) {
      return getQueryLink({
        href: link.value(origins[country], country.toLowerCase()),
      });
    }
    return typeof link === "object"
      ? link.value(origins[country], country.toLowerCase())
      : link;
  });
}

export function addParamsProduct(product) {
  return {
    ...product,
    href: getQueryLink(product),
  };
}

const relativeLanguageToCountry = {
  PL: "polish",
  PT: "portugal",
  ES: "spanish",
  CHDE: "german",
  CHFR: "french",
  DE: "germanDE",
  AT: "germanDE",
  HU: "Hungarian",
  FI: "finnish",
  FR: "french",
  CZ: "czech",
  SK: "slovak",
  DK: "danish",
  IT: "italian",
  SE: "swedish",
  UK: "english",
  NO: "norsk",
  NL: "dutch",
};

export function getQueryLink(item) {
  const template = getState("template");
  const country = getState("country");
  const ids = getState("ids");

  if (item.href === undefined) return undefined;
  if (item.href === null) return undefined;

  const queryLink = new URL(item.href);

  // Category query
  if (item.searchParams) {
    for (const [key, value] of item.searchParams.entries()) {
      // Get filter name
      const filterItem = filterNames.find((filter) => filter.title === key);
      const filterName = filterItem.data[relativeLanguageToCountry[country]];

      const allFilters = item.searchParams.get(key).split(",");

      queryLink.searchParams.delete(key, value);
      const collectFilters = [];
      allFilters.forEach((filterTitle) => {
        const filterItem = filterValues.find(
          (filter) => filter.title === filterTitle
        );
        const filterValue = filterItem.data[relativeLanguageToCountry[country]];
        collectFilters.push(handleSpace(handleSpecialCharacters(filterValue)));
      });
      queryLink.searchParams.append(
        handleSpecialCharacters(filterName),
        collectFilters.join(",")
      );
    }
  }

  if (template === "newsletter") {
    queryLink.searchParams.set("utm_source", "newsletter");
    queryLink.searchParams.set("utm_medium", "email");
    queryLink.searchParams.set("utm_campaign", ids[country]);
  }

  return queryLink.href;
}

function handleSpace(string) {
  let new_string = "";

  if (string.includes(" ")) {
    new_string = string.replaceAll(" ", "_");
    return new_string;
  } else {
    return string;
  }
}

function handleSpecialCharacters(filterValue) {
  const list_of_special_chars = {
    Ą: "A",
    ą: "a",
    ä: "a",
    á: "a",
    æ: "ae",
    Ę: "E",
    ę: "e",
    é: "e",
    Ó: "O",
    ó: "o",
    Ć: "C",
    ć: "c",
    Ł: "L",
    ł: "l",
    Ń: "N",
    ń: "n",
    Ś: "S",
    ś: "s",
    Ź: "Z",
    ź: "z",
    Ż: "Z",
    ž: "z",
    ż: "z",
    ü: "u",
    í: "i",
  };

  let string = "";
  const value = filterValue.value.split("");
  for (const item of value) {
    if (item in list_of_special_chars) {
      string += list_of_special_chars[item];
    } else {
      string += item;
    }
  }

  return string;
}

const filterNames = [
  {
    title: "Colour",
    data: {
      czech: {
        language: "czech",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Barva",
        iid: "184215792",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-15 14:01:22",
        last_by: "Martina Vargova",
      },
      spanish: {
        language: "spanish",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Color",
        iid: "183360140",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-09 15:35:10",
        last_by: "Sandra Paola Alvarez",
      },
      italian: {
        language: "italian",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Colore",
        iid: "183118120",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2021-03-16 12:21:50",
        last_by: "Simone Damiani",
      },
      english: {
        language: "english",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Colour",
        iid: "183099640",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-06 15:27:19",
        last_by: "Katarzyna Gościniec",
      },
      portugal: {
        language: "portugal",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Cor",
        iid: "183352065",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-09 13:19:28",
        last_by: "Pedro Patkoczy",
      },
      french: {
        language: "french",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Couleur",
        iid: "183128843",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-06 12:59:24",
        last_by: "Justyna Jarosiewicz",
      },
      slovak: {
        language: "slovak",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Farba",
        iid: "277521303",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2021-04-02 13:27:40",
        last_by: "Veronika Melosova",
      },
      german: {
        language: "german",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Farbe",
        iid: "183128844",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-06 12:59:24",
        last_by: "Justyna Jarosiewicz",
      },
      germanDE: {
        language: "germanDE",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Farbe",
        iid: "183128845",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-06 12:59:24",
        last_by: "Justyna Jarosiewicz",
      },
      swedish: {
        language: "swedish",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Färg",
        iid: "183179664",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-07 13:19:35",
        last_by: "Sara Sidorczuk",
      },
      norsk: {
        language: "norsk",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Farge",
        iid: "258378298",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2021-09-14 14:28:32",
        last_by: "Monika Poznańska",
      },
      danish: {
        language: "danish",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Farve",
        iid: "183379430",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-10 12:18:37",
        last_by: "Camilla Hansen",
      },
      dutch: {
        language: "dutch",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Kleur",
        iid: "192469219",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-05-22 17:27:27",
        last_by: "Michiel Straatman",
      },
      polish: {
        language: "polish",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Kolor",
        iid: "183128846",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-06 12:59:24",
        last_by: "Justyna Jarosiewicz",
      },
      Hungarian: {
        language: "Hungarian",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Szín",
        iid: "183273571",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-08 12:55:37",
        last_by: "Zsanett Fulop",
      },
      finnish: {
        language: "finnish",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Väri",
        iid: "183359502",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-09 15:13:35",
        last_by: "Aino Kyro",
      },
    },
  },
];

const filterValues = [
  {
    title: "Beige",
    data: {
      english: {
        language: "english",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "181493625",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-09 13:40:43",
        last_by: "Katarzyna Go\u015bciniec",
      },
      french: {
        language: "french",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "181541873",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-12 11:48:57",
        last_by: "Stephane Pasteur",
      },
      finnish: {
        language: "finnish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "181548865",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-12 12:06:15",
        last_by: "Aino Kyro",
      },
      italian: {
        language: "italian",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "181565398",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-12 12:50:17",
        last_by: "Simone Damiani",
      },
      spanish: {
        language: "spanish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "181589932",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-12 14:36:55",
        last_by: "Magdalena Jedraszak",
      },
      german: {
        language: "german",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "181765919",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-13 13:31:14",
        last_by: "Monika Pozna\u0144ska",
      },
      germanDE: {
        language: "germanDE",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "181765920",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-13 13:31:14",
        last_by: "Monika Pozna\u0144ska",
      },
      danish: {
        language: "danish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "181905910",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-15 11:09:43",
        last_by: "Camilla Hansen",
      },
      swedish: {
        language: "swedish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "181952544",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-15 16:14:40",
        last_by: "Izabela Kvist",
      },
      dutch: {
        language: "dutch",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "193185053",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-05-28 22:03:41",
        last_by: "Michiel Straatman",
      },
      norsk: {
        language: "norsk",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "258709743",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2020-07-01 14:25:32",
        last_by: "Damian Sala",
      },
      czech: {
        language: "czech",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "B\u00e9\u017eov\u00e1",
        iid: "181893401",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-15 09:57:16",
        last_by: "Martina Vargova",
      },
      slovak: {
        language: "slovak",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "B\u00e9\u017eov\u00e1",
        iid: "278363983",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-04-20 13:36:34",
        last_by: "Veronika Melosova",
      },
      polish: {
        language: "polish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Be\u017cowy",
        iid: "181765921",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-13 13:31:14",
        last_by: "Monika Pozna\u0144ska",
      },
      Hungarian: {
        language: "Hungarian",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "B\u00e9zs",
        iid: "181938525",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-15 14:27:23",
        last_by: "Boglarka Sebestyen",
      },
      portugal: {
        language: "portugal",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Creme",
        iid: "183355250",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-03-22 14:08:56",
        last_by: "Vitor Dos Santos Carmo ",
      },
      romanian: {
        language: "romanian",
        value: "",
        table_name: "sa_content_value",
        field_name: "value",
        id: 2609,
      },
    },
  },
  {
    title: "Natural",
    data: {
      finnish: {
        language: "finnish",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Luonnonv\u00e4ri",
        iid: "280491370",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-10-24 13:42:05",
        last_by: "Oona Jouste",
      },
      english: {
        language: "english",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Natural",
        iid: "280460053",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-17 06:45:50",
        last_by: "Katarzyna Go\u015bciniec",
      },
      portugal: {
        language: "portugal",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Natural",
        iid: "280481816",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-17 16:08:03",
        last_by: "Vitor Dos Santos Carmo ",
      },
      spanish: {
        language: "spanish",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Natural",
        iid: "280491026",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-18 08:34:08",
        last_by: "Ana Jakubik",
      },
      italian: {
        language: "italian",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Naturale",
        iid: "280476698",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-17 13:12:40",
        last_by: "Simone Damiani",
      },
      polish: {
        language: "polish",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Naturalny",
        iid: "280460054",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-17 06:45:50",
        last_by: "Katarzyna Go\u015bciniec",
      },
      french: {
        language: "french",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Naturel",
        iid: "280481654",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-17 15:58:06",
        last_by: "Raphael Pereira",
      },
      german: {
        language: "german",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Nat\u00fcrlich",
        iid: "280490121",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-18 07:51:31",
        last_by: "Justyna Bola",
      },
      germanDE: {
        language: "germanDE",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Nat\u00fcrlich",
        iid: "280490122",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-18 07:51:31",
        last_by: "Justyna Bola",
      },
      danish: {
        language: "danish",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Naturlig",
        iid: "280493376",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-18 11:32:18",
        last_by: "Ewa Papka",
      },
      norsk: {
        language: "norsk",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Naturlig",
        iid: "280494741",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-18 13:29:28",
        last_by: "Joanna Murawska",
      },
      swedish: {
        language: "swedish",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Naturlig",
        iid: "280526216",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-21 13:18:51",
        last_by: "Wiktor Malolepszy",
      },
      dutch: {
        language: "dutch",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Natuurlijk",
        iid: "280526089",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-21 12:56:56",
        last_by: "Marleen Bomhof",
      },
      slovak: {
        language: "slovak",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Pr\u00edrodn\u00e1",
        iid: "280480459",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-02-04 11:20:18",
        last_by: "Bibiana Vysokajova",
      },
      czech: {
        language: "czech",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "P\u0159\u00edrodn\u00ed",
        iid: "280482659",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-17 17:08:26",
        last_by: "Martina Rezaninova ",
      },
      Hungarian: {
        language: "Hungarian",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Term\u00e9szetes",
        iid: "280477871",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-17 13:46:13",
        last_by: "Patricia Czicza",
      },
    },
  },
  {
    title: "Light_Wood",
    data: {
      french: {
        language: "french",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Bois clair",
        iid: "181541884",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-12 11:48:57",
        last_by: "Stephane Pasteur",
      },
      portugal: {
        language: "portugal",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Castanho claro",
        iid: "183355261",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-03-22 14:08:57",
        last_by: "Vitor Dos Santos Carmo ",
      },
      german: {
        language: "german",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Heller Holzfarbton",
        iid: "181772900",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-13 14:19:09",
        last_by: "Elke Arheidt-Hofmann",
      },
      germanDE: {
        language: "germanDE",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Heller Holzfarbton",
        iid: "181772901",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-13 14:19:09",
        last_by: "Elke Arheidt-Hofmann",
      },
      polish: {
        language: "polish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Jasne drewno",
        iid: "200069653",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-08-22 11:06:48",
        last_by: "Justyna Jarosiewicz",
      },
      italian: {
        language: "italian",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Legno chiaro",
        iid: "181565409",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-12 12:50:18",
        last_by: "Simone Damiani",
      },
      dutch: {
        language: "dutch",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Lichte houtkleur",
        iid: "193185064",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2019-12-16 08:30:05",
        last_by: "Marleen Bomhof",
      },
      english: {
        language: "english",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Light Wood",
        iid: "181500418",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-09 14:19:16",
        last_by: "Katarzyna Go\u015bciniec",
      },
      swedish: {
        language: "swedish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Ljus tr\u00e4f\u00e4rg",
        iid: "181952555",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-15 16:14:41",
        last_by: "Izabela Kvist",
      },
      norsk: {
        language: "norsk",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Lyst tre",
        iid: "258709753",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-07-07 08:57:47",
        last_by: "Adriana Bogus",
      },
      danish: {
        language: "danish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Lyst Tr\u00e6",
        iid: "181905921",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-11-15 14:37:37",
        last_by: "Marta Borowska",
      },
      spanish: {
        language: "spanish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Madera clara",
        iid: "181589943",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-12 14:36:55",
        last_by: "Magdalena Jedraszak",
      },
      czech: {
        language: "czech",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Sv\u011btl\u00e9 d\u0159evo",
        iid: "181893412",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-15 09:57:17",
        last_by: "Martina Vargova",
      },
      slovak: {
        language: "slovak",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Svetl\u00e9 drevo",
        iid: "278363993",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-04-20 13:36:35",
        last_by: "Veronika Melosova",
      },
      finnish: {
        language: "finnish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Vaalea puu",
        iid: "181548876",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-12 12:06:15",
        last_by: "Aino Kyro",
      },
      Hungarian: {
        language: "Hungarian",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Vil\u00e1gos fa \u00e1rnyalat",
        iid: "181938536",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-15 14:27:23",
        last_by: "Boglarka Sebestyen",
      },
    },
  },
];
