import { getState } from "../main/initApp.js";
import { computeValue } from "./computeValue.js";

export function addParams({ links }) {
  const country = getState("country");
  const template = getState("template");
  const ids = getState("ids");

  return links.map((link) => {
    if ("value" in link) {
      return link.value;
    }

    let newValue = "";
    let value = "src" in link ? link.src : link.href;
    if ("type" in value) {
      newValue = computeValue({ ...link });
    }

    if ("query" in newValue) {
      const url = new URL(newValue.href);
      if (template.type === "newsletter") {
        url.searchParams.set("utm_source", "newsletter");
        url.searchParams.set("utm_medium", "email");
        url.searchParams.set("utm_campaign", ids[country]);
      }
      newValue = url;
    }

    return "src" in newValue ? newValue.src : newValue.href;
  });
}

export function addParamsProduct(product) {
  const template = getState("template");
  const country = getState("country");
  const ids = getState("ids");

  try {
    const url = new URL(product.href);
    if (template.type === "newsletter") {
      url.searchParams.set("utm_source", "newsletter");
      url.searchParams.set("utm_medium", "email");
      url.searchParams.set("utm_campaign", ids[country]);
    }
    return {
      ...product,
      href: url.href,
    };
  } catch (error) {
    Toastify({
      text: "Product url parse error.",
      escapeMarkup: false,
      duration: 3000,
    }).showToast();
    return;
  }
}

const relativeLanguageToCountry = {
  PL: "polish",
  PT: "portugal",
  ES: "spanish",
  CHDE: "german",
  CHFR: "french",
  DE: "germanDE",
  AT: "germanDE",
  HU: "Hungarian",
  FI: "finnish",
  FR: "french",
  CZ: "czech",
  SK: "slovak",
  DK: "danish",
  IT: "italian",
  SE: "swedish",
  UK: "english",
  NO: "norsk",
  NL: "dutch",
};

export function getQueryLink(item) {
  const template = getState("template");
  const country = getState("country");
  const ids = getState("ids");

  if (item.href === undefined) return undefined;
  if (item.href === null) return undefined;

  const queryLink = new URL(item.href);

  // Category query doesn't work properly.
  if (false) {
    for (const [key, value] of item.searchParams.entries()) {
      // Get filter name
      const filterItem = filterNames.find((filter) => filter.title === key);
      if (!filterItem) {
        throw new Error(`Filter ${key} not found.`);
      }
      const filterName = filterItem.data[relativeLanguageToCountry[country]];

      const allFilters = item.searchParams.get(key).split(",");

      queryLink.searchParams.delete(key, value);
      const collectFilters = [];
      allFilters.forEach((filterTitle) => {
        const filterItem = filterValues.find(
          (filter) => filter.title === filterTitle
        );
        const filterValue = filterItem.data[relativeLanguageToCountry[country]];
        collectFilters.push(handleSpace(handleSpecialCharacters(filterValue)));
      });
      queryLink.searchParams.append(
        handleSpace(handleSpecialCharacters(filterName)),
        collectFilters.join(",")
      );
    }
  }
  if (template.type === "newsletter") {
    queryLink.searchParams.set("utm_source", "newsletter");
    queryLink.searchParams.set("utm_medium", "email");
    queryLink.searchParams.set("utm_campaign", ids[country]);
  }

  return queryLink.href;
}

function handleSpace(string) {
  let new_string = "";

  if (string.includes(" ")) {
    new_string = string.replaceAll(" ", "_");
    return new_string;
  } else {
    return string;
  }
}

function handleSpecialCharacters(filterValue) {
  const list_of_special_chars = {
    Ą: "A",
    ą: "a",
    ä: "a",
    ã: "a",
    á: "a",
    Æ: "AE",
    æ: "ae",
    Ę: "E",
    ę: "e",
    é: "e",
    è: "e",
    ě: "e",
    Ó: "O",
    ó: "o",
    ő: "o",
    Ø: "o",
    Ć: "C",
    ć: "c",
    ç: "c",
    Ł: "L",
    ł: "l",
    Ń: "N",
    ń: "n",
    Ś: "S",
    ś: "s",
    š: "s",
    Ź: "Z",
    ź: "z",
    Ż: "Z",
    ž: "z",
    ż: "z",
    ü: "u",
    ů: "u",
    Ü: "U",
    ű: "u",
    ř: "r",
    í: "i",
  };

  let string = "";
  const value = filterValue.value.split("");
  for (const item of value) {
    if (item in list_of_special_chars) {
      string += list_of_special_chars[item];
    } else {
      string += item;
    }
  }

  return string;
}

const filterNames = [
  {
    title: "Material",
    data: {
      Hungarian: {
        language: "Hungarian",
        table_name_id: "447",
        field_name_id: "1033",
        id: "517",
        value: "Anyag",
        iid: "183273278",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-08 12:53:36",
        last_by: "Zsanett Fulop",
      },
      dutch: {
        language: "dutch",
        table_name_id: "447",
        field_name_id: "1033",
        id: "517",
        value: "Materiaal",
        iid: "192469240",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2022-03-11 07:11:09",
        last_by: "Katarzyna Gościniec",
      },
      finnish: {
        language: "finnish",
        table_name_id: "447",
        field_name_id: "1033",
        id: "517",
        value: "Materiaalit",
        iid: "183358782",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-09 14:34:18",
        last_by: "Aino Kyro",
      },
      english: {
        language: "english",
        table_name_id: "447",
        field_name_id: "1033",
        id: "517",
        value: "Material",
        iid: "182967071",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-11-16 07:26:25",
        last_by: "Katarzyna Gościniec",
      },
      german: {
        language: "german",
        table_name_id: "447",
        field_name_id: "1033",
        id: "517",
        value: "Material",
        iid: "183186950",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-07 13:57:07",
        last_by: "Elke Arheidt-Hofmann",
      },
      germanDE: {
        language: "germanDE",
        table_name_id: "447",
        field_name_id: "1033",
        id: "517",
        value: "Material",
        iid: "183186951",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-07 13:57:07",
        last_by: "Elke Arheidt-Hofmann",
      },
      swedish: {
        language: "swedish",
        table_name_id: "447",
        field_name_id: "1033",
        id: "517",
        value: "Material",
        iid: "183191219",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-07 15:03:35",
        last_by: "Sara Sidorczuk",
      },
      portugal: {
        language: "portugal",
        table_name_id: "447",
        field_name_id: "1033",
        id: "517",
        value: "Material_principal",
        iid: "183352047",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-09-05 09:40:55",
        last_by: "Pedro Patkoczy",
      },
      spanish: {
        language: "spanish",
        table_name_id: "447",
        field_name_id: "1033",
        id: "517",
        value: "Material_principal",
        iid: "183360107",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-09 15:32:24",
        last_by: "Sandra Paola Alvarez",
      },
      czech: {
        language: "czech",
        table_name_id: "447",
        field_name_id: "1033",
        id: "517",
        value: "Materiál",
        iid: "184215536",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-15 13:59:51",
        last_by: "Martina Vargova",
      },
      slovak: {
        language: "slovak",
        table_name_id: "447",
        field_name_id: "1033",
        id: "517",
        value: "Materiál",
        iid: "277519046",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2021-04-02 13:15:18",
        last_by: "Veronika Melosova",
      },
      romanian: {
        language: "romanian",
        table_name_id: "447",
        field_name_id: "1033",
        id: "517",
        value: "Material",
        iid: "334363092",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2024-04-08 10:06:37",
        last_by: "",
      },
      italian: {
        language: "italian",
        table_name_id: "447",
        field_name_id: "1033",
        id: "517",
        value: "Materiale_primario",
        iid: "183117891",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2022-08-01 09:59:33",
        last_by: "Rosario Badia",
      },
      danish: {
        language: "danish",
        table_name_id: "447",
        field_name_id: "1033",
        id: "517",
        value: "Materiale",
        iid: "183379446",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-10 12:21:09",
        last_by: "Camilla Hansen",
      },
      norsk: {
        language: "norsk",
        table_name_id: "447",
        field_name_id: "1033",
        id: "517",
        value: "Materiale",
        iid: "258381204",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2020-06-26 12:59:45",
        last_by: "Monika Kosc-Byczkowska",
      },
      polish: {
        language: "polish",
        table_name_id: "447",
        field_name_id: "1033",
        id: "517",
        value: "Materiał",
        iid: "183279855",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-08 13:40:34",
        last_by: "Monika Poznańska",
      },
      french: {
        language: "french",
        table_name_id: "447",
        field_name_id: "1033",
        id: "517",
        value: "Materiau",
        iid: "183194330",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-07 15:34:30",
        last_by: "Stephane Pasteur",
      },
    },
  },
  {
    title: "Colour",
    data: {
      czech: {
        language: "czech",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Barva",
        iid: "184215792",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-15 14:01:22",
        last_by: "Martina Vargova",
      },
      spanish: {
        language: "spanish",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Color",
        iid: "183360140",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-09 15:35:10",
        last_by: "Sandra Paola Alvarez",
      },
      italian: {
        language: "italian",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Colore",
        iid: "183118120",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2021-03-16 12:21:50",
        last_by: "Simone Damiani",
      },
      english: {
        language: "english",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Colour",
        iid: "183099640",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-06 15:27:19",
        last_by: "Katarzyna Gościniec",
      },
      portugal: {
        language: "portugal",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Cor",
        iid: "183352065",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-09 13:19:28",
        last_by: "Pedro Patkoczy",
      },
      french: {
        language: "french",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Couleur",
        iid: "183128843",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-06 12:59:24",
        last_by: "Justyna Jarosiewicz",
      },
      slovak: {
        language: "slovak",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Farba",
        iid: "277521303",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2021-04-02 13:27:40",
        last_by: "Veronika Melosova",
      },
      german: {
        language: "german",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Farbe",
        iid: "183128844",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-06 12:59:24",
        last_by: "Justyna Jarosiewicz",
      },
      germanDE: {
        language: "germanDE",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Farbe",
        iid: "183128845",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-06 12:59:24",
        last_by: "Justyna Jarosiewicz",
      },
      swedish: {
        language: "swedish",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Färg",
        iid: "183179664",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-07 13:19:35",
        last_by: "Sara Sidorczuk",
      },
      norsk: {
        language: "norsk",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Farge",
        iid: "258378298",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2021-09-14 14:28:32",
        last_by: "Monika Poznańska",
      },
      danish: {
        language: "danish",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Farve",
        iid: "183379430",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-10 12:18:37",
        last_by: "Camilla Hansen",
      },
      dutch: {
        language: "dutch",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Kleur",
        iid: "192469219",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-05-22 17:27:27",
        last_by: "Michiel Straatman",
      },
      polish: {
        language: "polish",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Kolor",
        iid: "183128846",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-06 12:59:24",
        last_by: "Justyna Jarosiewicz",
      },
      Hungarian: {
        language: "Hungarian",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Szín",
        iid: "183273571",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-08 12:55:37",
        last_by: "Zsanett Fulop",
      },
      finnish: {
        language: "finnish",
        table_name_id: "447",
        field_name_id: "1033",
        id: "533",
        value: "Väri",
        iid: "183359502",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2018-03-09 15:13:35",
        last_by: "Aino Kyro",
      },
    },
  },
  {
    title: "Seat_Material",
    data: {
      finnish: {
        language: "finnish",
        table_name_id: "447",
        field_name_id: "1033",
        id: "589",
        value: "Istuimen materiaali",
        iid: "223623095",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2019-03-18 13:38:13",
        last_by: "Milla Hietala",
      },
      dutch: {
        language: "dutch",
        table_name_id: "447",
        field_name_id: "1033",
        id: "589",
        value: "Materiaal zitting",
        iid: "225795478",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2019-04-07 11:51:08",
        last_by: "Michiel Straatman",
      },
      portugal: {
        language: "portugal",
        table_name_id: "447",
        field_name_id: "1033",
        id: "589",
        value: "Material do assento",
        iid: "223618716",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2019-03-18 13:20:13",
        last_by: "Pedro Patkoczy",
      },
      spanish: {
        language: "spanish",
        table_name_id: "447",
        field_name_id: "1033",
        id: "589",
        value: "Material de asiento",
        iid: "223668099",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2019-03-18 15:52:19",
        last_by: "Ana Jakubik",
      },
      czech: {
        language: "czech",
        table_name_id: "447",
        field_name_id: "1033",
        id: "589",
        value: "Materiál sedáku",
        iid: "223624301",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2019-03-18 13:44:04",
        last_by: "Jaroslav Zbortek",
      },
      slovak: {
        language: "slovak",
        table_name_id: "447",
        field_name_id: "1033",
        id: "589",
        value: "Materiál sedadla",
        iid: "277524233",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2021-11-25 12:18:01",
        last_by: "Bibiana Vysokajova",
      },
      romanian: {
        language: "romanian",
        table_name_id: "447",
        field_name_id: "1033",
        id: "589",
        value: "Material scaun",
        iid: "334363084",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2024-04-08 10:06:37",
        last_by: "",
      },
      italian: {
        language: "italian",
        table_name_id: "447",
        field_name_id: "1033",
        id: "589",
        value: "Materiale della seduta",
        iid: "224319720",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2019-03-24 10:45:32",
        last_by: "Simone Damiani",
      },
      french: {
        language: "french",
        table_name_id: "447",
        field_name_id: "1033",
        id: "589",
        value: "Matériau du siège",
        iid: "223670412",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2019-03-18 16:02:26",
        last_by: "Michel Lambion",
      },
      polish: {
        language: "polish",
        table_name_id: "447",
        field_name_id: "1033",
        id: "589",
        value: "Materiał siedziska",
        iid: "231543788",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2019-06-17 15:03:13",
        last_by: "Patrycja Staniszewska",
      },
      english: {
        language: "english",
        table_name_id: "447",
        field_name_id: "1033",
        id: "589",
        value: "Seat Material",
        iid: "223614670",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2019-03-18 12:54:23",
        last_by: "Katarzyna Gościniec",
      },
      norsk: {
        language: "norsk",
        table_name_id: "447",
        field_name_id: "1033",
        id: "589",
        value: "Setemateriale",
        iid: "258369613",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2020-06-26 11:32:13",
        last_by: "Monika Kosc-Byczkowska",
      },
      swedish: {
        language: "swedish",
        table_name_id: "447",
        field_name_id: "1033",
        id: "589",
        value: "Sitsmaterial",
        iid: "223638393",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2019-03-18 14:41:24",
        last_by: "Lila Sommarstam",
      },
      german: {
        language: "german",
        table_name_id: "447",
        field_name_id: "1033",
        id: "589",
        value: "Sitzmaterial",
        iid: "231543790",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2019-06-17 15:05:54",
        last_by: "Patrycja Staniszewska",
      },
      germanDE: {
        language: "germanDE",
        table_name_id: "447",
        field_name_id: "1033",
        id: "589",
        value: "Sitzmaterial",
        iid: "231544089",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2019-06-17 15:08:49",
        last_by: "Patrycja Staniszewska",
      },
      danish: {
        language: "danish",
        table_name_id: "447",
        field_name_id: "1033",
        id: "589",
        value: "Sæde materiale",
        iid: "223684748",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2019-03-18 18:26:33",
        last_by: "Marta Borowska",
      },
      Hungarian: {
        language: "Hungarian",
        table_name_id: "447",
        field_name_id: "1033",
        id: "589",
        value: "Ülőfelület anyaga",
        iid: "224448698",
        unchecked: "1",
        updated: "0",
        table_name: "sa_field",
        field_name: "field_name",
        last_on: "2019-03-25 08:58:36",
        last_by: "Adrienn Lendvai-Beszedics",
      },
    },
  },
];

// https://www.prologistics.info/react/autodescription/sa_contents/content/4/
// https://www.prologistics.info/react/autodescription/sa_contents/content/354/
// Filter Material
// Path sa_content.content_values
const filterValues = [
  {
    title: "Beige",
    data: {
      english: {
        language: "english",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "181493625",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-09 13:40:43",
        last_by: "Katarzyna Go\u015bciniec",
      },
      french: {
        language: "french",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "181541873",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-12 11:48:57",
        last_by: "Stephane Pasteur",
      },
      finnish: {
        language: "finnish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "181548865",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-12 12:06:15",
        last_by: "Aino Kyro",
      },
      italian: {
        language: "italian",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "181565398",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-12 12:50:17",
        last_by: "Simone Damiani",
      },
      spanish: {
        language: "spanish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "181589932",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-12 14:36:55",
        last_by: "Magdalena Jedraszak",
      },
      german: {
        language: "german",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "181765919",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-13 13:31:14",
        last_by: "Monika Pozna\u0144ska",
      },
      germanDE: {
        language: "germanDE",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "181765920",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-13 13:31:14",
        last_by: "Monika Pozna\u0144ska",
      },
      danish: {
        language: "danish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "181905910",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-15 11:09:43",
        last_by: "Camilla Hansen",
      },
      swedish: {
        language: "swedish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "181952544",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-15 16:14:40",
        last_by: "Izabela Kvist",
      },
      dutch: {
        language: "dutch",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "193185053",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-05-28 22:03:41",
        last_by: "Michiel Straatman",
      },
      norsk: {
        language: "norsk",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Beige",
        iid: "258709743",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2020-07-01 14:25:32",
        last_by: "Damian Sala",
      },
      czech: {
        language: "czech",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "B\u00e9\u017eov\u00e1",
        iid: "181893401",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-15 09:57:16",
        last_by: "Martina Vargova",
      },
      slovak: {
        language: "slovak",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "B\u00e9\u017eov\u00e1",
        iid: "278363983",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-04-20 13:36:34",
        last_by: "Veronika Melosova",
      },
      polish: {
        language: "polish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Be\u017cowy",
        iid: "181765921",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-13 13:31:14",
        last_by: "Monika Pozna\u0144ska",
      },
      Hungarian: {
        language: "Hungarian",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "B\u00e9zs",
        iid: "181938525",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-15 14:27:23",
        last_by: "Boglarka Sebestyen",
      },
      portugal: {
        language: "portugal",
        table_name_id: "446",
        field_name_id: "58",
        id: "2609",
        value: "Creme",
        iid: "183355250",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-03-22 14:08:56",
        last_by: "Vitor Dos Santos Carmo ",
      },
      romanian: {
        language: "romanian",
        value: "",
        table_name: "sa_content_value",
        field_name: "value",
        id: 2609,
      },
    },
  },
  {
    title: "Wood",
    data: {
      french: {
        language: "french",
        table_name_id: "446",
        field_name_id: "58",
        id: "3199",
        value: "Bois solide",
        iid: "204732771",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-10-02 11:44:49",
        last_by: "Katarzyna Gościniec",
      },
      czech: {
        language: "czech",
        table_name_id: "446",
        field_name_id: "58",
        id: "3199",
        value: "Dřevo",
        iid: "204732766",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-12-15 14:13:53",
        last_by: "Monika Manova",
      },
      slovak: {
        language: "slovak",
        table_name_id: "446",
        field_name_id: "58",
        id: "3199",
        value: "Drevo",
        iid: "278461454",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2023-01-02 07:36:08",
        last_by: "Bibiana Vysokajova",
      },
      polish: {
        language: "polish",
        table_name_id: "446",
        field_name_id: "58",
        id: "3199",
        value: "Drewno",
        iid: "204732776",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-07-19 13:09:17",
        last_by: "Natalia Kowalewska",
      },
      norsk: {
        language: "norsk",
        table_name_id: "446",
        field_name_id: "58",
        id: "3199",
        value: "Heltre",
        iid: "258805077",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-09-07 10:59:10",
        last_by: "Adriana Bogus",
      },
      Hungarian: {
        language: "Hungarian",
        table_name_id: "446",
        field_name_id: "58",
        id: "3199",
        value: "Keményfa",
        iid: "204732774",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-10-02 11:44:49",
        last_by: "Katarzyna Gościniec",
      },
      italian: {
        language: "italian",
        table_name_id: "446",
        field_name_id: "58",
        id: "3199",
        value: "Legno massiccio",
        iid: "204732775",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-10-02 11:44:49",
        last_by: "Katarzyna Gościniec",
      },
      romanian: {
        language: "romanian",
        table_name_id: "446",
        field_name_id: "58",
        id: "3199",
        value: "Lemn masiv",
        iid: "334365538",
        unchecked: "0",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2024-04-08 10:06:40",
        last_by: "",
      },
      portugal: {
        language: "portugal",
        table_name_id: "446",
        field_name_id: "58",
        id: "3199",
        value: "Madeira maciça",
        iid: "204732777",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-12-15 14:13:53",
        last_by: "Monika Manova",
      },
      spanish: {
        language: "spanish",
        table_name_id: "446",
        field_name_id: "58",
        id: "3199",
        value: "Madera maciza",
        iid: "204732778",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-10-02 11:44:49",
        last_by: "Katarzyna Gościniec",
      },
      dutch: {
        language: "dutch",
        table_name_id: "446",
        field_name_id: "58",
        id: "3199",
        value: "Massief hout",
        iid: "204732768",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-10-02 11:44:49",
        last_by: "Katarzyna Gościniec",
      },
      danish: {
        language: "danish",
        table_name_id: "446",
        field_name_id: "58",
        id: "3199",
        value: "Massiv træ",
        iid: "204732767",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-10-02 11:44:49",
        last_by: "Katarzyna Gościniec",
      },
      german: {
        language: "german",
        table_name_id: "446",
        field_name_id: "58",
        id: "3199",
        value: "Massivholz",
        iid: "204732772",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-10-02 11:44:49",
        last_by: "Katarzyna Gościniec",
      },
      germanDE: {
        language: "germanDE",
        table_name_id: "446",
        field_name_id: "58",
        id: "3199",
        value: "Massivholz",
        iid: "204732773",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-10-02 11:44:49",
        last_by: "Katarzyna Gościniec",
      },
      swedish: {
        language: "swedish",
        table_name_id: "446",
        field_name_id: "58",
        id: "3199",
        value: "Massivt trä",
        iid: "204732779",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-10-02 11:44:49",
        last_by: "Katarzyna Gościniec",
      },
      finnish: {
        language: "finnish",
        table_name_id: "446",
        field_name_id: "58",
        id: "3199",
        value: "Puu",
        iid: "204732770",
        unchecked: "1",
        updated: "1",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2023-02-06 11:10:07",
        last_by: "Oona Jouste",
      },
      english: {
        language: "english",
        table_name_id: "446",
        field_name_id: "58",
        id: "3199",
        value: "Wood",
        iid: "204732769",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-12-16 13:05:10",
        last_by: "Katarzyna Wiśniewska",
      },
    },
  },
  {
    title: "Natural",
    data: {
      finnish: {
        language: "finnish",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Luonnonv\u00e4ri",
        iid: "280491370",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-10-24 13:42:05",
        last_by: "Oona Jouste",
      },
      english: {
        language: "english",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Natural",
        iid: "280460053",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-17 06:45:50",
        last_by: "Katarzyna Go\u015bciniec",
      },
      portugal: {
        language: "portugal",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Natural",
        iid: "280481816",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-17 16:08:03",
        last_by: "Vitor Dos Santos Carmo ",
      },
      spanish: {
        language: "spanish",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Natural",
        iid: "280491026",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-18 08:34:08",
        last_by: "Ana Jakubik",
      },
      italian: {
        language: "italian",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Naturale",
        iid: "280476698",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-17 13:12:40",
        last_by: "Simone Damiani",
      },
      polish: {
        language: "polish",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Naturalny",
        iid: "280460054",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-17 06:45:50",
        last_by: "Katarzyna Go\u015bciniec",
      },
      french: {
        language: "french",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Naturel",
        iid: "280481654",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-17 15:58:06",
        last_by: "Raphael Pereira",
      },
      german: {
        language: "german",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Nat\u00fcrlich",
        iid: "280490121",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-18 07:51:31",
        last_by: "Justyna Bola",
      },
      germanDE: {
        language: "germanDE",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Nat\u00fcrlich",
        iid: "280490122",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-18 07:51:31",
        last_by: "Justyna Bola",
      },
      danish: {
        language: "danish",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Naturlig",
        iid: "280493376",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-18 11:32:18",
        last_by: "Ewa Papka",
      },
      norsk: {
        language: "norsk",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Naturlig",
        iid: "280494741",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-18 13:29:28",
        last_by: "Joanna Murawska",
      },
      swedish: {
        language: "swedish",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Naturlig",
        iid: "280526216",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-21 13:18:51",
        last_by: "Wiktor Malolepszy",
      },
      dutch: {
        language: "dutch",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Natuurlijk",
        iid: "280526089",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-21 12:56:56",
        last_by: "Marleen Bomhof",
      },
      slovak: {
        language: "slovak",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Pr\u00edrodn\u00e1",
        iid: "280480459",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-02-04 11:20:18",
        last_by: "Bibiana Vysokajova",
      },
      czech: {
        language: "czech",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "P\u0159\u00edrodn\u00ed",
        iid: "280482659",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-17 17:08:26",
        last_by: "Martina Rezaninova ",
      },
      Hungarian: {
        language: "Hungarian",
        table_name_id: "446",
        field_name_id: "58",
        id: "5274",
        value: "Term\u00e9szetes",
        iid: "280477871",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-06-17 13:46:13",
        last_by: "Patricia Czicza",
      },
    },
  },
  {
    title: "Light_Wood",
    data: {
      french: {
        language: "french",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Bois clair",
        iid: "181541884",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-12 11:48:57",
        last_by: "Stephane Pasteur",
      },
      portugal: {
        language: "portugal",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Castanho claro",
        iid: "183355261",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-03-22 14:08:57",
        last_by: "Vitor Dos Santos Carmo ",
      },
      german: {
        language: "german",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Heller Holzfarbton",
        iid: "181772900",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-13 14:19:09",
        last_by: "Elke Arheidt-Hofmann",
      },
      germanDE: {
        language: "germanDE",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Heller Holzfarbton",
        iid: "181772901",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-13 14:19:09",
        last_by: "Elke Arheidt-Hofmann",
      },
      polish: {
        language: "polish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Jasne drewno",
        iid: "200069653",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-08-22 11:06:48",
        last_by: "Justyna Jarosiewicz",
      },
      italian: {
        language: "italian",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Legno chiaro",
        iid: "181565409",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-12 12:50:18",
        last_by: "Simone Damiani",
      },
      dutch: {
        language: "dutch",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Lichte houtkleur",
        iid: "193185064",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2019-12-16 08:30:05",
        last_by: "Marleen Bomhof",
      },
      english: {
        language: "english",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Light Wood",
        iid: "181500418",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-09 14:19:16",
        last_by: "Katarzyna Go\u015bciniec",
      },
      swedish: {
        language: "swedish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Ljus tr\u00e4f\u00e4rg",
        iid: "181952555",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-15 16:14:41",
        last_by: "Izabela Kvist",
      },
      norsk: {
        language: "norsk",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Lyst tre",
        iid: "258709753",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-07-07 08:57:47",
        last_by: "Adriana Bogus",
      },
      danish: {
        language: "danish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Lyst Tr\u00e6",
        iid: "181905921",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-11-15 14:37:37",
        last_by: "Marta Borowska",
      },
      spanish: {
        language: "spanish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Madera clara",
        iid: "181589943",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-12 14:36:55",
        last_by: "Magdalena Jedraszak",
      },
      czech: {
        language: "czech",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Sv\u011btl\u00e9 d\u0159evo",
        iid: "181893412",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-15 09:57:17",
        last_by: "Martina Vargova",
      },
      slovak: {
        language: "slovak",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Svetl\u00e9 drevo",
        iid: "278363993",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-04-20 13:36:35",
        last_by: "Veronika Melosova",
      },
      finnish: {
        language: "finnish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Vaalea puu",
        iid: "181548876",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-12 12:06:15",
        last_by: "Aino Kyro",
      },
      Hungarian: {
        language: "Hungarian",
        table_name_id: "446",
        field_name_id: "58",
        id: "2620",
        value: "Vil\u00e1gos fa \u00e1rnyalat",
        iid: "181938536",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-02-15 14:27:23",
        last_by: "Boglarka Sebestyen",
      },
    },
  },
  {
    title: "Faux_Leather",
    data: {
      french: {
        language: "french",
        table_name_id: "446",
        field_name_id: "58",
        id: "2885",
        value: "Cuir PU",
        iid: "183278056",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-12-15 18:57:20",
        last_by: "Neige Barry",
      },
      italian: {
        language: "italian",
        table_name_id: "446",
        field_name_id: "58",
        id: "2885",
        value: "Scamosciato sintetico",
        iid: "183121714",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-12-23 09:59:40",
        last_by: "Rafal Benich",
      },
      english: {
        language: "english",
        table_name_id: "446",
        field_name_id: "58",
        id: "2885",
        value: "Faux Leather",
        iid: "182981084",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-12-23 09:59:40",
        last_by: "Rafal Benich",
      },
      finnish: {
        language: "finnish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2885",
        value: "Keinonahka",
        iid: "183362877",
        unchecked: "1",
        updated: "1",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-12-23 09:59:40",
        last_by: "Rafal Benich",
      },
      swedish: {
        language: "swedish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2885",
        value: "Konstläder",
        iid: "183200065",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-12-23 09:59:40",
        last_by: "Rafal Benich",
      },
      german: {
        language: "german",
        table_name_id: "446",
        field_name_id: "58",
        id: "2885",
        value: "Kunstleder",
        iid: "183133399",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-03-06 14:06:58",
        last_by: "Elke Arheidt-Hofmann",
      },
      germanDE: {
        language: "germanDE",
        table_name_id: "446",
        field_name_id: "58",
        id: "2885",
        value: "Kunstleder",
        iid: "183133400",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-03-06 14:06:58",
        last_by: "Elke Arheidt-Hofmann",
      },
      dutch: {
        language: "dutch",
        table_name_id: "446",
        field_name_id: "58",
        id: "2885",
        value: "Kunstleer",
        iid: "192469324",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-12-23 09:59:40",
        last_by: "Rafal Benich",
      },
      norsk: {
        language: "norsk",
        table_name_id: "446",
        field_name_id: "58",
        id: "2885",
        value: "Kunstskinn",
        iid: "258805062",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2020-11-10 10:36:21",
        last_by: "Adriana Bogus",
      },
      Hungarian: {
        language: "Hungarian",
        table_name_id: "446",
        field_name_id: "58",
        id: "2885",
        value: "Műbőr",
        iid: "183306894",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-12-23 09:59:40",
        last_by: "Rafal Benich",
      },
      portugal: {
        language: "portugal",
        table_name_id: "446",
        field_name_id: "58",
        id: "2885",
        value: "Pele sintética",
        iid: "183357384",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-12-23 09:59:40",
        last_by: "Rafal Benich",
      },
      spanish: {
        language: "spanish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2885",
        value: "Piel sintética",
        iid: "183363065",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-03-09 16:50:20",
        last_by: "Sandra Paola Alvarez",
      },
      romanian: {
        language: "romanian",
        table_name_id: "446",
        field_name_id: "58",
        id: "2885",
        value: "Piele artificială",
        iid: "334365006",
        unchecked: "0",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2024-04-08 10:06:40",
        last_by: "",
      },
      polish: {
        language: "polish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2885",
        value: "Skóra ekologiczna",
        iid: "183136700",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-12-23 09:59:40",
        last_by: "Rafal Benich",
      },
      slovak: {
        language: "slovak",
        table_name_id: "446",
        field_name_id: "58",
        id: "2885",
        value: "Umelá koža",
        iid: "278461440",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-04-22 12:49:29",
        last_by: "Veronika Melosova",
      },
      czech: {
        language: "czech",
        table_name_id: "446",
        field_name_id: "58",
        id: "2885",
        value: "Umělá kůže",
        iid: "183779386",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-12-15 14:21:12",
        last_by: "Jessica Stok",
      },
      danish: {
        language: "danish",
        table_name_id: "446",
        field_name_id: "58",
        id: "2885",
        value: "Kunstlaeder",
        iid: "183604481",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2018-03-13 12:54:47",
        last_by: "Camilla Hansen",
      },
    },
  },
  {
    title: "Faux_Fur",
    data: {
      romanian: {
        language: "romanian",
        table_name_id: "446",
        field_name_id: "58",
        id: "3887",
        value: "Blana falsă",
        iid: "334365092",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2024-04-08 10:06:40",
        last_by: "",
      },
      english: {
        language: "english",
        table_name_id: "446",
        field_name_id: "58",
        id: "3887",
        value: "Faux Fur",
        iid: "254100255",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2020-03-31 12:08:53",
        last_by: "Przemyslaw Robert",
      },
      italian: {
        language: "italian",
        table_name_id: "446",
        field_name_id: "58",
        id: "3887",
        value: "Finta pelliccia",
        iid: "254100261",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-08-10 07:18:53",
        last_by: "Rosario Badia",
      },
      french: {
        language: "french",
        table_name_id: "446",
        field_name_id: "58",
        id: "3887",
        value: "Fourrure synthétique",
        iid: "254100257",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2020-03-31 12:08:53",
        last_by: "Przemyslaw Robert",
      },
      norsk: {
        language: "norsk",
        table_name_id: "446",
        field_name_id: "58",
        id: "3887",
        value: "Fuskepels",
        iid: "258603291",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-01-28 12:20:07",
        last_by: "Adriana Bogus",
      },
      swedish: {
        language: "swedish",
        table_name_id: "446",
        field_name_id: "58",
        id: "3887",
        value: "Fuskpäls",
        iid: "254100265",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2020-03-31 12:08:53",
        last_by: "Przemyslaw Robert",
      },
      portugal: {
        language: "portugal",
        table_name_id: "446",
        field_name_id: "58",
        id: "3887",
        value: "Imitação de pele",
        iid: "254100263",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2020-03-31 12:08:53",
        last_by: "Przemyslaw Robert",
      },
      finnish: {
        language: "finnish",
        table_name_id: "446",
        field_name_id: "58",
        id: "3887",
        value: "Keinoturkis",
        iid: "254100256",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-05-17 12:02:54",
        last_by: "Oona Jouste",
      },
      danish: {
        language: "danish",
        table_name_id: "446",
        field_name_id: "58",
        id: "3887",
        value: "Kunstig pels",
        iid: "254100253",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2020-03-31 12:08:53",
        last_by: "Przemyslaw Robert",
      },
      Hungarian: {
        language: "Hungarian",
        table_name_id: "446",
        field_name_id: "58",
        id: "3887",
        value: "Műszőrme",
        iid: "254100260",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2020-03-31 12:08:53",
        last_by: "Przemyslaw Robert",
      },
      dutch: {
        language: "dutch",
        table_name_id: "446",
        field_name_id: "58",
        id: "3887",
        value: "Nepbont",
        iid: "254100254",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2020-03-31 12:08:53",
        last_by: "Przemyslaw Robert",
      },
      spanish: {
        language: "spanish",
        table_name_id: "446",
        field_name_id: "58",
        id: "3887",
        value: "Pelo sintético",
        iid: "254100264",
        unchecked: "1",
        updated: "1",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2024-04-15 10:50:39",
        last_by: "Cristina Cancillo",
      },
      polish: {
        language: "polish",
        table_name_id: "446",
        field_name_id: "58",
        id: "3887",
        value: "Sztuczne futro",
        iid: "254100262",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2020-03-31 12:08:53",
        last_by: "Przemyslaw Robert",
      },
      czech: {
        language: "czech",
        table_name_id: "446",
        field_name_id: "58",
        id: "3887",
        value: "Umělá kožešina",
        iid: "254100252",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2020-03-31 12:08:53",
        last_by: "Przemyslaw Robert",
      },
      slovak: {
        language: "slovak",
        table_name_id: "446",
        field_name_id: "58",
        id: "3887",
        value: "Umelá kožušina",
        iid: "277541565",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-04-03 19:42:00",
        last_by: "Veronika Melosova",
      },
      german: {
        language: "german",
        table_name_id: "446",
        field_name_id: "58",
        id: "3887",
        value: "Webpelz",
        iid: "254100258",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2020-03-31 12:08:53",
        last_by: "Przemyslaw Robert",
      },
      germanDE: {
        language: "germanDE",
        table_name_id: "446",
        field_name_id: "58",
        id: "3887",
        value: "Webpelz",
        iid: "254100259",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2020-03-31 12:08:53",
        last_by: "Przemyslaw Robert",
      },
    },
  },
  {
    title: "Leather",
    data: {
      Hungarian: {
        language: "Hungarian",
        table_name_id: "446",
        field_name_id: "58",
        id: "622",
        value: "Bőr",
        iid: "172916151",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2017-12-11 08:35:20",
        last_by: "",
      },
      french: {
        language: "french",
        table_name_id: "446",
        field_name_id: "58",
        id: "622",
        value: "Cuir",
        iid: "172916152",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2017-12-11 08:35:20",
        last_by: "",
      },
      german: {
        language: "german",
        table_name_id: "446",
        field_name_id: "58",
        id: "622",
        value: "Echtleder",
        iid: "172916153",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2017-12-11 08:35:20",
        last_by: "",
      },
      germanDE: {
        language: "germanDE",
        table_name_id: "446",
        field_name_id: "58",
        id: "622",
        value: "Echtleder",
        iid: "175247109",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2017-12-20 19:43:05",
        last_by: "",
      },
      norsk: {
        language: "norsk",
        table_name_id: "446",
        field_name_id: "58",
        id: "622",
        value: "Ekte skinn",
        iid: "258585045",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2020-11-10 09:37:06",
        last_by: "Adriana Bogus",
      },
      slovak: {
        language: "slovak",
        table_name_id: "446",
        field_name_id: "58",
        id: "622",
        value: "Koza",
        iid: "277541484",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2021-04-03 19:41:55",
        last_by: "Veronika Melosova",
      },
      czech: {
        language: "czech",
        table_name_id: "446",
        field_name_id: "58",
        id: "622",
        value: "Kůže",
        iid: "172916154",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2017-12-11 08:35:20",
        last_by: "",
      },
      swedish: {
        language: "swedish",
        table_name_id: "446",
        field_name_id: "58",
        id: "622",
        value: "Läder",
        iid: "172916159",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2023-01-13 15:36:35",
        last_by: "Nilla Kristensson",
      },
      english: {
        language: "english",
        table_name_id: "446",
        field_name_id: "58",
        id: "622",
        value: "Leather",
        iid: "172916155",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2017-12-11 08:35:20",
        last_by: "",
      },
      dutch: {
        language: "dutch",
        table_name_id: "446",
        field_name_id: "58",
        id: "622",
        value: "Leer",
        iid: "172916157",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2017-12-11 08:35:20",
        last_by: "",
      },
      finnish: {
        language: "finnish",
        table_name_id: "446",
        field_name_id: "58",
        id: "622",
        value: "Nahka",
        iid: "172916158",
        unchecked: "1",
        updated: "1",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2017-12-11 08:35:20",
        last_by: "",
      },
      portugal: {
        language: "portugal",
        table_name_id: "446",
        field_name_id: "58",
        id: "622",
        value: "Pele",
        iid: "172916160",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2017-12-11 08:35:20",
        last_by: "",
      },
      italian: {
        language: "italian",
        table_name_id: "446",
        field_name_id: "58",
        id: "622",
        value: "Pelle Naturale",
        iid: "172916163",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2022-07-19 13:53:49",
        last_by: "Rosario Badia",
      },
      spanish: {
        language: "spanish",
        table_name_id: "446",
        field_name_id: "58",
        id: "622",
        value: "Piel",
        iid: "172916161",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2017-12-11 08:35:20",
        last_by: "",
      },
      romanian: {
        language: "romanian",
        table_name_id: "446",
        field_name_id: "58",
        id: "622",
        value: "Piele naturală",
        iid: "334365942",
        unchecked: "0",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2024-04-08 10:06:41",
        last_by: "",
      },
      polish: {
        language: "polish",
        table_name_id: "446",
        field_name_id: "58",
        id: "622",
        value: "Skóra naturalna",
        iid: "172916162",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2017-12-11 08:35:20",
        last_by: "",
      },
      danish: {
        language: "danish",
        table_name_id: "446",
        field_name_id: "58",
        id: "622",
        value: "Ægte læder",
        iid: "172916164",
        unchecked: "1",
        updated: "0",
        table_name: "sa_content_value",
        field_name: "Value",
        last_on: "2017-12-11 08:35:20",
        last_by: "",
      },
    },
  },
];
